CREATE TABLE [dbo].[UserTask]
(
	[UserTaskId] INT IDENTITY(1,1) NOT NULL,
	[TaskId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[StateId] INT NOT NULL,

	CONSTRAINT [PK_UserTask] PRIMARY KEY CLUSTERED([UserTaskId] ASC),

	CONSTRAINT [FK_UserTask_TaskTrack] FOREIGN KEY ([TaskId]) REFERENCES [TaskTrack](TaskTrackId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	CONSTRAINT [FK_UserTask_UserProfile] FOREIGN KEY ([UserId]) REFERENCES [UserProfile](UserId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	CONSTRAINT [FK_UserTask_TaskState] FOREIGN KEY ([StateId]) REFERENCES [TaskState](StateId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)